# Generated by Django 2.1.5 on 2019-01-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bucketlist',
            new_name='Idea',
        ),
    ]
