# Generated by Django 2.1.5 on 2019-01-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_idea_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='imageURL',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='idea',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idea',
            name='potential_solution',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='idea',
            name='problem',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
