# Generated by Django 2.1.5 on 2019-01-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190128_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='coderCount',
            field=models.IntegerField(default=0),
        ),
    ]
